# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 943057d6c85d7cddf731cb5a4d8198eab0f53c0c97311c5d691e7ba627477ac06f557455bc3df6436044454589dcb64010c2f44ed31254500ab4fa5c06c429a3

test:
  secret_key_base: 779dfe0dd4c81e07c06fc174a534bcafba1db57be23d7561e8aceb285040a64a4c414bb5a33a76cd4a57559f20b4dc09f6da7f310069d5a0f58d5f63a37b1a2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
